version: "3.8"
services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php_app
        volumes:
            - .:/var/www
        networks:
            - app-network
        environment:
            # For Xdebug
            PHP_IDE_CONFIG: serverName=Docker
        restart: unless-stopped

    nginx:
        image: nginx:latest
        container_name: nginx_app
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network
        restart: unless-stopped
    db:
        container_name: mysql_app
        image: mysql:latest
        ports:
            - "3306:3306"
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ./db-data:/var/lib/mysql
        networks:
            - app-network
        restart: unless-stopped

networks:
    app-network:
        driver: bridge
